In [1]:
import pandas as pd

In [3]:
file_path = "../../Dataset/raw/Data_for_repository.csv"

In [4]:
df = pd.read_csv(file_path)
print("Dataset loaded successfully")

Dataset loaded successfully

In [5]:
rows, columns = df.shape

print("Number of records: ", rows)
print("Number of columns: ", columns)

Number of records:  1698
Number of columns:  14

In [9]:
print("Column names: ")
for col in df.columns:
    print(df)

Column names:
                             Movie_Name Release_Period Whether_Remake  \
0                           Golden Boys         Normal             No
1                         Kaccha Limboo        Holiday             No
2                      Not A Love Story        Holiday             No
3                            Qaidi Band        Holiday             No
4                             Chaatwali        Holiday             No
...                                 ...            ...            ...
1693                         Fight Club        Holiday             No
1694                 Strings Of Paasion         Normal             No
1695              Dunno Y Na Jaane Kyun         Normal             No
1696  Taj Mahal - An Eternal Love Story         Normal             No
1697                   Mr. Hot Mr. Kool         Normal             No

     Whether_Franchise     Genre New_Actor New_Director New_Music_Director  \
0                   No  suspense       Yes           No                 No
1                   No     drama       Yes           No                Yes
2                   No  thriller        No           No                 No
3                   No     drama       Yes           No                 No
4                   No     adult       Yes          Yes                Yes
...                ...       ...       ...          ...                ...
1693                No    action        No          Yes                 No
1694                No     drama        No          Yes                Yes
1695                No     drama        No           No                 No
1696                No     drama        No          Yes                 No
1697                No    comedy        No           No                Yes

             Lead_Star               Director   Music_Director  \
0         Jeet Goswami             Ravi Varma    Baba Jagirdar
1     Karan Bhanushali          Sagar Ballary  Amardeep Nijjer
2           Mahie Gill        Ram Gopal Verma   Sandeep Chowta
3           Aadar Jain           Habib Faisal     Amit Trivedi
4           Aadil Khan             Aadil Khan     Babloo Ustad
...                ...                    ...              ...
1693        Zayed Khan          Vikram Chopra           Pritam
1694       Zeenat Aman  Sanghamitra Chaudhuri       Dev Sikdar
1695       Zeenat Aman          Sanjay Sharma           Nikhil
1696       Zulfi Sayed             Akbar Khan          Naushad
1697       Zulfi Sayed           Partho Ghosh   Rishi - Ranjit

      Number_of_Screens  Revenue(INR)  Budget(INR)
0                     5       5000000        85000
1                    75      15000000       825000
2                   525      75000000     56700000
3                   800     210000000      4500000
4                     1       1000000      1075000
...                 ...           ...          ...
1693                375      82500000     88862500
1694                 10       8000000        70000
1695                 20      12500000       850000
1696                135     100000000     31065000
1697                 30      27500000      1300000

[1698 rows x 14 columns]
                             Movie_Name Release_Period Whether_Remake  \
0                           Golden Boys         Normal             No
1                         Kaccha Limboo        Holiday             No
2                      Not A Love Story        Holiday             No
3                            Qaidi Band        Holiday             No
4                             Chaatwali        Holiday             No
...                                 ...            ...            ...
1693                         Fight Club        Holiday             No
1694                 Strings Of Paasion         Normal             No
1695              Dunno Y Na Jaane Kyun         Normal             No
1696  Taj Mahal - An Eternal Love Story         Normal             No
1697                   Mr. Hot Mr. Kool         Normal             No

     Whether_Franchise     Genre New_Actor New_Director New_Music_Director  \
0                   No  suspense       Yes           No                 No
1                   No     drama       Yes           No                Yes
2                   No  thriller        No           No                 No
3                   No     drama       Yes           No                 No
4                   No     adult       Yes          Yes                Yes
...                ...       ...       ...          ...                ...
1693                No    action        No          Yes                 No
1694                No     drama        No          Yes                Yes
1695                No     drama        No           No                 No
1696                No     drama        No          Yes                 No
1697                No    comedy        No           No                Yes

             Lead_Star               Director   Music_Director  \
0         Jeet Goswami             Ravi Varma    Baba Jagirdar
1     Karan Bhanushali          Sagar Ballary  Amardeep Nijjer
2           Mahie Gill        Ram Gopal Verma   Sandeep Chowta
3           Aadar Jain           Habib Faisal     Amit Trivedi
4           Aadil Khan             Aadil Khan     Babloo Ustad
...                ...                    ...              ...
1693        Zayed Khan          Vikram Chopra           Pritam
1694       Zeenat Aman  Sanghamitra Chaudhuri       Dev Sikdar
1695       Zeenat Aman          Sanjay Sharma           Nikhil
1696       Zulfi Sayed             Akbar Khan          Naushad
1697       Zulfi Sayed           Partho Ghosh   Rishi - Ranjit

      Number_of_Screens  Revenue(INR)  Budget(INR)
0                     5       5000000        85000
1                    75      15000000       825000
2                   525      75000000     56700000
3                   800     210000000      4500000
4                     1       1000000      1075000
...                 ...           ...          ...
1693                375      82500000     88862500
1694                 10       8000000        70000
1695                 20      12500000       850000
1696                135     100000000     31065000
1697                 30      27500000      1300000

[1698 rows x 14 columns]
                             Movie_Name Release_Period Whether_Remake  \
0                           Golden Boys         Normal             No
1                         Kaccha Limboo        Holiday             No
2                      Not A Love Story        Holiday             No
3                            Qaidi Band        Holiday             No
4                             Chaatwali        Holiday             No
...                                 ...            ...            ...
1693                         Fight Club        Holiday             No
1694                 Strings Of Paasion         Normal             No
1695              Dunno Y Na Jaane Kyun         Normal             No
1696  Taj Mahal - An Eternal Love Story         Normal             No
1697                   Mr. Hot Mr. Kool         Normal             No

     Whether_Franchise     Genre New_Actor New_Director New_Music_Director  \
0                   No  suspense       Yes           No                 No
1                   No     drama       Yes           No                Yes
2                   No  thriller        No           No                 No
3                   No     drama       Yes           No                 No
4                   No     adult       Yes          Yes                Yes
...                ...       ...       ...          ...                ...
1693                No    action        No          Yes                 No
1694                No     drama        No          Yes                Yes
1695                No     drama        No           No                 No
1696                No     drama        No          Yes                 No
1697                No    comedy        No           No                Yes

             Lead_Star               Director   Music_Director  \
0         Jeet Goswami             Ravi Varma    Baba Jagirdar
1     Karan Bhanushali          Sagar Ballary  Amardeep Nijjer
2           Mahie Gill        Ram Gopal Verma   Sandeep Chowta
3           Aadar Jain           Habib Faisal     Amit Trivedi
4           Aadil Khan             Aadil Khan     Babloo Ustad
...                ...                    ...              ...
1693        Zayed Khan          Vikram Chopra           Pritam
1694       Zeenat Aman  Sanghamitra Chaudhuri       Dev Sikdar
1695       Zeenat Aman          Sanjay Sharma           Nikhil
1696       Zulfi Sayed             Akbar Khan          Naushad
1697       Zulfi Sayed           Partho Ghosh   Rishi - Ranjit

      Number_of_Screens  Revenue(INR)  Budget(INR)
0                     5       5000000        85000
1                    75      15000000       825000
2                   525      75000000     56700000
3                   800     210000000      4500000
4                     1       1000000      1075000
...                 ...           ...          ...
1693                375      82500000     88862500
1694                 10       8000000        70000
1695                 20      12500000       850000
1696                135     100000000     31065000
1697                 30      27500000      1300000

[1698 rows x 14 columns]
                             Movie_Name Release_Period Whether_Remake  \
0                           Golden Boys         Normal             No
1                         Kaccha Limboo        Holiday             No
2                      Not A Love Story        Holiday             No
3                            Qaidi Band        Holiday             No
4                             Chaatwali        Holiday             No
...                                 ...            ...            ...
1693                         Fight Club        Holiday             No
1694                 Strings Of Paasion         Normal             No
1695              Dunno Y Na Jaane Kyun         Normal             No
1696  Taj Mahal - An Eternal Love Story         Normal             No
1697                   Mr. Hot Mr. Kool         Normal             No

     Whether_Franchise     Genre New_Actor New_Director New_Music_Director  \
0                   No  suspense       Yes           No                 No
1                   No     drama       Yes           No                Yes
2                   No  thriller        No           No                 No
3                   No     drama       Yes           No                 No
4                   No     adult       Yes          Yes                Yes
...                ...       ...       ...          ...                ...
1693                No    action        No          Yes                 No
1694                No     drama        No          Yes                Yes
1695                No     drama        No           No                 No
1696                No     drama        No          Yes                 No
1697                No    comedy        No           No                Yes

             Lead_Star               Director   Music_Director  \
0         Jeet Goswami             Ravi Varma    Baba Jagirdar
1     Karan Bhanushali          Sagar Ballary  Amardeep Nijjer
2           Mahie Gill        Ram Gopal Verma   Sandeep Chowta
3           Aadar Jain           Habib Faisal     Amit Trivedi
4           Aadil Khan             Aadil Khan     Babloo Ustad
...                ...                    ...              ...
1693        Zayed Khan          Vikram Chopra           Pritam
1694       Zeenat Aman  Sanghamitra Chaudhuri       Dev Sikdar
1695       Zeenat Aman          Sanjay Sharma           Nikhil
1696       Zulfi Sayed             Akbar Khan          Naushad
1697       Zulfi Sayed           Partho Ghosh   Rishi - Ranjit

      Number_of_Screens  Revenue(INR)  Budget(INR)
0                     5       5000000        85000
1                    75      15000000       825000
2                   525      75000000     56700000
3                   800     210000000      4500000
4                     1       1000000      1075000
...                 ...           ...          ...
1693                375      82500000     88862500
1694                 10       8000000        70000
1695                 20      12500000       850000
1696                135     100000000     31065000
1697                 30      27500000      1300000

[1698 rows x 14 columns]
                             Movie_Name Release_Period Whether_Remake  \
0                           Golden Boys         Normal             No
1                         Kaccha Limboo        Holiday             No
2                      Not A Love Story        Holiday             No
3                            Qaidi Band        Holiday             No
4                             Chaatwali        Holiday             No
...                                 ...            ...            ...
1693                         Fight Club        Holiday             No
1694                 Strings Of Paasion         Normal             No
1695              Dunno Y Na Jaane Kyun         Normal             No
1696  Taj Mahal - An Eternal Love Story         Normal             No
1697                   Mr. Hot Mr. Kool         Normal             No

     Whether_Franchise     Genre New_Actor New_Director New_Music_Director  \
0                   No  suspense       Yes           No                 No
1                   No     drama       Yes           No                Yes
2                   No  thriller        No           No                 No
3                   No     drama       Yes           No                 No
4                   No     adult       Yes          Yes                Yes
...                ...       ...       ...          ...                ...
1693                No    action        No          Yes                 No
1694                No     drama        No          Yes                Yes
1695                No     drama        No           No                 No
1696                No     drama        No          Yes                 No
1697                No    comedy        No           No                Yes

             Lead_Star               Director   Music_Director  \
0         Jeet Goswami             Ravi Varma    Baba Jagirdar
1     Karan Bhanushali          Sagar Ballary  Amardeep Nijjer
2           Mahie Gill        Ram Gopal Verma   Sandeep Chowta
3           Aadar Jain           Habib Faisal     Amit Trivedi
4           Aadil Khan             Aadil Khan     Babloo Ustad
...                ...                    ...              ...
1693        Zayed Khan          Vikram Chopra           Pritam
1694       Zeenat Aman  Sanghamitra Chaudhuri       Dev Sikdar
1695       Zeenat Aman          Sanjay Sharma           Nikhil
1696       Zulfi Sayed             Akbar Khan          Naushad
1697       Zulfi Sayed           Partho Ghosh   Rishi - Ranjit

      Number_of_Screens  Revenue(INR)  Budget(INR)
0                     5       5000000        85000
1                    75      15000000       825000
2                   525      75000000     56700000
3                   800     210000000      4500000
4                     1       1000000      1075000
...                 ...           ...          ...
1693                375      82500000     88862500
1694                 10       8000000        70000
1695                 20      12500000       850000
1696                135     100000000     31065000
1697                 30      27500000      1300000

[1698 rows x 14 columns]
                             Movie_Name Release_Period Whether_Remake  \
0                           Golden Boys         Normal             No
1                         Kaccha Limboo        Holiday             No
2                      Not A Love Story        Holiday             No
3                            Qaidi Band        Holiday             No
4                             Chaatwali        Holiday             No
...                                 ...            ...            ...
1693                         Fight Club        Holiday             No
1694                 Strings Of Paasion         Normal             No
1695              Dunno Y Na Jaane Kyun         Normal             No
1696  Taj Mahal - An Eternal Love Story         Normal             No
1697                   Mr. Hot Mr. Kool         Normal             No

     Whether_Franchise     Genre New_Actor New_Director New_Music_Director  \
0                   No  suspense       Yes           No                 No
1                   No     drama       Yes           No                Yes
2                   No  thriller        No           No                 No
3                   No     drama       Yes           No                 No
4                   No     adult       Yes          Yes                Yes
...                ...       ...       ...          ...                ...
1693                No    action        No          Yes                 No
1694                No     drama        No          Yes                Yes
1695                No     drama        No           No                 No
1696                No     drama        No          Yes                 No
1697                No    comedy        No           No                Yes

             Lead_Star               Director   Music_Director  \
0         Jeet Goswami             Ravi Varma    Baba Jagirdar
1     Karan Bhanushali          Sagar Ballary  Amardeep Nijjer
2           Mahie Gill        Ram Gopal Verma   Sandeep Chowta
3           Aadar Jain           Habib Faisal     Amit Trivedi
4           Aadil Khan             Aadil Khan     Babloo Ustad
...                ...                    ...              ...
1693        Zayed Khan          Vikram Chopra           Pritam
1694       Zeenat Aman  Sanghamitra Chaudhuri       Dev Sikdar
1695       Zeenat Aman          Sanjay Sharma           Nikhil
1696       Zulfi Sayed             Akbar Khan          Naushad
1697       Zulfi Sayed           Partho Ghosh   Rishi - Ranjit

      Number_of_Screens  Revenue(INR)  Budget(INR)
0                     5       5000000        85000
1                    75      15000000       825000
2                   525      75000000     56700000
3                   800     210000000      4500000
4                     1       1000000      1075000
...                 ...           ...          ...
1693                375      82500000     88862500
1694                 10       8000000        70000
1695                 20      12500000       850000
1696                135     100000000     31065000
1697                 30      27500000      1300000

[1698 rows x 14 columns]
                             Movie_Name Release_Period Whether_Remake  \
0                           Golden Boys         Normal             No
1                         Kaccha Limboo        Holiday             No
2                      Not A Love Story        Holiday             No
3                            Qaidi Band        Holiday             No
4                             Chaatwali        Holiday             No
...                                 ...            ...            ...
1693                         Fight Club        Holiday             No
1694                 Strings Of Paasion         Normal             No
1695              Dunno Y Na Jaane Kyun         Normal             No
1696  Taj Mahal - An Eternal Love Story         Normal             No
1697                   Mr. Hot Mr. Kool         Normal             No

     Whether_Franchise     Genre New_Actor New_Director New_Music_Director  \
0                   No  suspense       Yes           No                 No
1                   No     drama       Yes           No                Yes

In [10]:
print("Data types: ")
print(df.dtypes)

Data types:
Movie_Name              str
Release_Period          str
Whether_Remake          str
Whether_Franchise       str
Genre                   str
New_Actor               str
New_Director            str
New_Music_Director      str
Lead_Star               str
Director                str
Music_Director          str
Number_of_Screens     int64
Revenue(INR)          int64
Budget(INR)           int64
dtype: object

In [12]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1698 entries, 0 to 1697
Data columns (total 14 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Movie_Name          1698 non-null   str
 1   Release_Period      1698 non-null   str
 2   Whether_Remake      1698 non-null   str
 3   Whether_Franchise   1698 non-null   str
 4   Genre               1698 non-null   str
 5   New_Actor           1698 non-null   str
 6   New_Director        1698 non-null   str
 7   New_Music_Director  1698 non-null   str
 8   Lead_Star           1698 non-null   str
 9   Director            1698 non-null   str
 10  Music_Director      1698 non-null   str
 11  Number_of_Screens   1698 non-null   int64
 12  Revenue(INR)        1698 non-null   int64
 13  Budget(INR)         1698 non-null   int64
dtypes: int64(3), str(11)
memory usage: 185.8 KB

In [15]:
missing_values = df.isnull().sum()

print("Missing values in each column:")
print(missing_values)

Missing values in each column:
Movie_Name            0
Release_Period        0
Whether_Remake        0
Whether_Franchise     0
Genre                 0
New_Actor             0
New_Director          0
New_Music_Director    0
Lead_Star             0
Director              0
Music_Director        0
Number_of_Screens     0
Revenue(INR)          0
Budget(INR)           0
dtype: int64

In [16]:
missing_percentage = (df.isnull().sum() / len(df)) * 100

print("Missing value percentage: ")
print(missing_percentage)

Missing value percentage:
Movie_Name            0.0
Release_Period        0.0
Whether_Remake        0.0
Whether_Franchise     0.0
Genre                 0.0
New_Actor             0.0
New_Director          0.0
New_Music_Director    0.0
Lead_Star             0.0
Director              0.0
Music_Director        0.0
Number_of_Screens     0.0
Revenue(INR)          0.0
Budget(INR)           0.0
dtype: float64

In [17]:
duplicate_count = df.duplicated().sum()

print("Number of duplicated records: ", duplicate_count)

Number of duplicated records:  2

In [18]:
print("Number of unique values in each column: ")
for column in df.columns:
    print(column, ":", df[column].nunique())

Number of unique values in each column:
Movie_Name : 1695
Release_Period : 2
Whether_Remake : 2
Whether_Franchise : 2
Genre : 14
New_Actor : 2
New_Director : 2
New_Music_Director : 2
Lead_Star : 764
Director : 1048
Music_Director : 630
Number_of_Screens : 147
Revenue(INR) : 184
Budget(INR) : 1104

In [19]:
categorical_columns = [
    "Release_Period",
    "Whether_Remake",
    "Whether_Franchise",
    "Genre",
    "New_Actor",
    "New_Director",
    "New_Music_Director"
]

for column in categorical_columns:
    print("\n", column)
    print(df[column].value_counts())

 Release_Period
Release_Period
Normal     1064
Holiday     634
Name: count, dtype: int64

 Whether_Remake
Whether_Remake
No     1627
Yes      71
Name: count, dtype: int64

 Whether_Franchise
Whether_Franchise
No     1616
Yes      82
Name: count, dtype: int64

 Genre
Genre
drama           639
comedy          284
thriller        212
love_story      133
action          127
rom__com         95
adult            78
horror           53
suspense         30
masala           16
mythological     14
fantasy          13
animation         3
documentary       1
Name: count, dtype: int64

 New_Actor
New_Actor
No     1243
Yes     455
Name: count, dtype: int64

 New_Director
New_Director
No     882
Yes    816
Name: count, dtype: int64

 New_Music_Director
New_Music_Director
No     1144
Yes     554
Name: count, dtype: int64

In [20]:
df.describe()

       Number_of_Screens  Revenue(INR)   Budget(INR)
count        1698.000000  1.698000e+03  1.698000e+03
mean          553.831567  1.501674e+08  2.377287e+08
std           782.951839  2.434838e+08  6.134398e+08
min             1.000000  3.250000e+05  7.250000e+03
25%            30.000000  1.500000e+07  1.150000e+06
50%           200.000000  5.500000e+07  1.240000e+07
75%           800.000000  1.900000e+08  1.778325e+08
max          4600.000000  2.100000e+09  8.016120e+09

In [21]:
df.describe(include="all")

,Movie_Name,Release_Period,Whether_Remake,Whether_Franchise,Genre,New_Actor,New_Director,New_Music_Director,Lead_Star,Director,Music_Director,Number_of_Screens,Revenue(INR),Budget(INR)
count,1698,1698,1698,1698,1698,1698,1698,1698,1698,1698,1698,1698.000000,1.698000e+03,1.698000e+03
unique,1695,2,2,2,14,2,2,2,764,1048,630,NaN,NaN,NaN
top,Game,Normal,No,No,drama,No,No,No,Akshay Kumar,Ram Gopal Verma,Pritam,NaN,NaN,NaN
freq,2,1064,1627,1616,639,1243,882,1144,48,18,92,NaN,NaN,NaN
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,553.831567,1.501674e+08,2.377287e+08
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,782.951839,2.434838e+08,6.134398e+08
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,3.250000e+05,7.250000e+03
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,30.000000,1.500000e+07,1.150000e+06
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,200.000000,5.500000e+07,1.240000e+07
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,800.000000,1.900000e+08,1.778325e+08
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4600.000000,2.100000e+09,8.016120e+09

In [23]:
print("Target variable: Revenue(INR)")

print("\nMinimum revenue:", df["Revenue(INR)"].min())
print("Maximum revenue:", df["Revenue(INR)"].max())
print("Average revenue:", df["Revenue(INR)"].mean())
print("Median revenue:", df["Revenue(INR)"].median())

Target variable: Revenue(INR)

Minimum revenue: 325000
Maximum revenue: 2100000000
Average revenue: 150167388.10365134
Median revenue: 55000000.0

In [24]:
numerical_columns = ["Number_of_Screens", "Revenue(INR)", "Budget(INR)"]
df[numerical_columns].describe()

       Number_of_Screens  Revenue(INR)   Budget(INR)
count        1698.000000  1.698000e+03  1.698000e+03
mean          553.831567  1.501674e+08  2.377287e+08
std           782.951839  2.434838e+08  6.134398e+08
min             1.000000  3.250000e+05  7.250000e+03
25%            30.000000  1.500000e+07  1.150000e+06
50%           200.000000  5.500000e+07  1.240000e+07
75%           800.000000  1.900000e+08  1.778325e+08
max          4600.000000  2.100000e+09  8.016120e+09

In [25]:
df.head(10)

,Movie_Name,Release_Period,Whether_Remake,Whether_Franchise,Genre,New_Actor,New_Director,New_Music_Director,Lead_Star,Director,Music_Director,Number_of_Screens,Revenue(INR),Budget(INR)
0,Golden Boys,Normal,No,No,suspense,Yes,No,No,Jeet Goswami,Ravi Varma,Baba Jagirdar,5,5000000,85000
1,Kaccha Limboo,Holiday,No,No,drama,Yes,No,Yes,Karan Bhanushali,Sagar Ballary,Amardeep Nijjer,75,15000000,825000
2,Not A Love Story,Holiday,No,No,thriller,No,No,No,Mahie Gill,Ram Gopal Verma,Sandeep Chowta,525,75000000,56700000
3,Qaidi Band,Holiday,No,No,drama,Yes,No,No,Aadar Jain,Habib Faisal,Amit Trivedi,800,210000000,4500000
4,Chaatwali,Holiday,No,No,adult,Yes,Yes,Yes,Aadil Khan,Aadil Khan,Babloo Ustad,1,1000000,1075000
5,Shuttlecock Boys,Normal,No,No,comedy,Yes,Yes,Yes,Aakar Kaushik,Hemant Gaba,Avinash Baghel,10,5000000,170000
6,Dirty Marriage,Holiday,No,No,adult,Yes,No,Yes,Aakash,Priyanka,Dharma,2,1500000,35000
7,Future To Bright Hai Ji,Holiday,No,No,drama,No,Yes,Yes,Aamir Bashir,Sanjay Amar,Amir Ali,30,15000000,825000
8,Ghajini,Holiday,Yes,No,action,No,Yes,No,Aamir Khan,A.R. Murugadoss,A.R. Rehman,1550,520000000,1945820000
9,Taare Zameen Par,Holiday,No,No,drama,No,Yes,No,Aamir Khan,Aamir Khan,Shankar - Ehsaan - Loy,500,180000000,875785000

In [26]:
df.tail(10)

,Movie_Name,Release_Period,Whether_Remake,Whether_Franchise,Genre,New_Actor,New_Director,New_Music_Director,Lead_Star,Director,Music_Director,Number_of_Screens,Revenue(INR),Budget(INR)
1688,Hate Story 3,Normal,No,Yes,thriller,No,No,Yes,Zarine Khan,Vishal Pandya,Baman,2600,200000000,622125000
1689,Sharafat Gayi Tel Lene,Normal,No,No,comedy,No,No,Yes,Zayed Khan,Gurmmeet Singh,Faridkot,450,70000000,5700000
1690,Love Breakups Zindagi,Normal,No,No,love_story,No,Yes,No,Zayed Khan,Sahil Sangha,Salim - Sulaiman,325,100000000,20600000
1691,Rocky,Normal,No,No,drama,No,No,No,Zayed Khan,Suresh Krishna,Himesh Reshammiya,225,92500000,30400000
1692,Speed,Holiday,Yes,No,thriller,No,No,No,Zayed Khan,Vikram Bhatt,Pritam,200,90000000,15800000
1693,Fight Club,Holiday,No,No,action,No,Yes,No,Zayed Khan,Vikram Chopra,Pritam,375,82500000,88862500
1694,Strings Of Paasion,Normal,No,No,drama,No,Yes,Yes,Zeenat Aman,Sanghamitra Chaudhuri,Dev Sikdar,10,8000000,70000
1695,Dunno Y Na Jaane Kyun,Normal,No,No,drama,No,No,No,Zeenat Aman,Sanjay Sharma,Nikhil,20,12500000,850000
1696,Taj Mahal - An Eternal Love Story,Normal,No,No,drama,No,Yes,No,Zulfi Sayed,Akbar Khan,Naushad,135,100000000,31065000
1697,Mr. Hot Mr. Kool,Normal,No,No,comedy,No,No,Yes,Zulfi Sayed,Partho Ghosh,Rishi - Ranjit,30,27500000,1300000