In [1]:
import pandas as pd
import numpy as np

In [2]:
file_path = "../../Dataset/processed/cleaned_movie_data.csv"

df = pd.read_csv(file_path)

print("Dataset loaded successfully")
print("Shape:", df.shape)

Dataset loaded successfully
Shape: (1696, 14)

In [3]:
df = df.drop(columns=["Movie_Name"])

print("Movie_Name removed")
print("Shape: ", df.shape)

Movie_Name removed
Shape:  (1696, 13)

In [4]:
X = df.drop(columns=["Revenue(INR)"])
y = df["Revenue(INR)"]

print("Features: ")
print(X.columns.tolist())

print("Target: ")
print("Revenue(INR)")

Features:
['Release_Period', 'Whether_Remake', 'Whether_Franchise', 'Genre', 'New_Actor', 'New_Director', 'New_Music_Director', 'Lead_Star', 'Director', 'Music_Director', 'Number_of_Screens', 'Budget(INR)']
Target:
Revenue(INR)

In [5]:
categorical_columns = [
    "Release_Period",
    "Whether_Remake",
    "Whether_Franchise",
    "Genre",
    "New_Actor",
    "New_Director",
    "New_Music_Director",
    "Lead_Star",
    "Director",
    "Music_Director"
]

numerical_columns = [
    "Number_of_Screens",
    "Budget(INR)"
]

print("Categorical features:")
print(categorical_columns)

print("\nNumerical features:")
print(numerical_columns)

Categorical features:
['Release_Period', 'Whether_Remake', 'Whether_Franchise', 'Genre', 'New_Actor', 'New_Director', 'New_Music_Director', 'Lead_Star', 'Director', 'Music_Director']

Numerical features:
['Number_of_Screens', 'Budget(INR)']

In [6]:
for column in categorical_columns:
    print("\n" + column)
    print(df[column].unique())

Release_Period
<StringArray>
['Normal', 'Holiday']
Length: 2, dtype: str

Whether_Remake
<StringArray>
['No', 'Yes']
Length: 2, dtype: str

Whether_Franchise
<StringArray>
['No', 'Yes']
Length: 2, dtype: str

Genre
<StringArray>
[    'suspense',        'drama',     'thriller',        'adult',
       'comedy',       'action',   'love_story',     'rom__com',
       'horror',      'fantasy',       'masala', 'mythological',
    'animation',  'documentary']
Length: 14, dtype: str

New_Actor
<StringArray>
['Yes', 'No']
Length: 2, dtype: str

New_Director
<StringArray>
['No', 'Yes']
Length: 2, dtype: str

New_Music_Director
<StringArray>
['No', 'Yes']
Length: 2, dtype: str

Lead_Star
<StringArray>
[    'Jeet Goswami', 'Karan Bhanushali',       'Mahie Gill',
       'Aadar Jain',       'Aadil Khan',    'Aakar Kaushik',
           'Aakash',     'Aamir Bashir',       'Aamir Khan',
    'Aanamika Bawa',
 ...
 'Yogendra Chouhan',  'Yugboah Garewal',      'Yugraj Jain',
    'Yukta Mookhey',      'Zaira Wasim',    'Zakir Hussain',
      'Zarine Khan',       'Zayed Khan',      'Zeenat Aman',
      'Zulfi Sayed']
Length: 764, dtype: str

Director
<StringArray>
[           'Ravi Varma',         'Sagar Ballary',       'Ram Gopal Verma',
          'Habib Faisal',            'Aadil Khan',           'Hemant Gaba',
              'Priyanka',           'Sanjay Amar',       'A.R. Murugadoss',
            'Aamir Khan',
 ...
        'Monazir Hasain',         'Sanjeev Nanda',       'Arshad Siddiqui',
        'Advait Chandan',      'Vineet Khetrapal',          'Sahil Sangha',
        'Suresh Krishna',         'Vikram Chopra', 'Sanghamitra Chaudhuri',
            'Akbar Khan']
Length: 1048, dtype: str

Music_Director
<StringArray>
[         'Baba Jagirdar',        'Amardeep Nijjer',         'Sandeep Chowta',
           'Amit Trivedi',           'Babloo Ustad',         'Avinash Baghel',
                 'Dharma',               'Amir Ali',            'A.R. Rehman',
 'Shankar - Ehsaan - Loy',
 ...
         'Praveen Kunwar',            'Sanjay Gite',          'Rajesh Pillay',
              'Hirju Roy',             'Aman Shlok',                  'Baman',
               'Faridkot',             'Dev Sikdar',                'Naushad',
         'Rishi - Ranjit']
Length: 630, dtype: str

In [7]:
X_encoded = pd.get_dummies(
    X,
    columns=categorical_columns,
    drop_first=True
)

print("Shape before encoding: ", X.shape)
print("Shape after encoding: ", X_encoded.shape)

Shape before encoding:  (1696, 12)
Shape after encoding:  (1696, 2460)

In [8]:
X_encoded = X_encoded.astype(int)

print(X_encoded.dtypes)

Number_of_Screens                    int64
Budget(INR)                          int64
Release_Period_Normal                int64
Whether_Remake_Yes                   int64
Whether_Franchise_Yes                int64
                                     ...
Music_Director_Yuvan Shankar Raja    int64
Music_Director_Zakir Hussain         int64
Music_Director_Zubeen Garg           int64
Music_Director_Zubin Balaporia       int64
Music_Director_Zubunnisa Bangash     int64
Length: 2460, dtype: object

In [9]:
print("Final feature shape:", X_encoded.shape)

X_encoded.head()

Final feature shape: (1696, 2460)

,Number_of_Screens,Budget(INR),Release_Period_Normal,Whether_Remake_Yes,Whether_Franchise_Yes,Genre_adult,Genre_animation,Genre_comedy,Genre_documentary,Genre_drama,...,Music_Director_Vivek Philip,Music_Director_Vivek Prakash,Music_Director_Vivek Priyadarshan,Music_Director_Wayne Sharpe,Music_Director_Yasin Darbar,Music_Director_Yuvan Shankar Raja,Music_Director_Zakir Hussain,Music_Director_Zubeen Garg,Music_Director_Zubin Balaporia,Music_Director_Zubunnisa Bangash
0,5,85000,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,75,825000,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
2,525,56700000,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,800,4500000,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
4,1,1075000,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [10]:
print("Target shape:", y.shape)

print("\nTarget statistics:")
print(y.describe())

Target shape: (1696,)

Target statistics:
count    1.696000e+03
mean     1.501293e+08
std      2.435648e+08
min      3.250000e+05
25%      1.500000e+07
50%      5.500000e+07
75%      1.900000e+08
max      2.100000e+09
Name: Revenue(INR), dtype: float64

In [11]:
print("Missing values in features:")
print(X_encoded.isnull().sum().sum())

print("\nMissing values in target:")
print(y.isnull().sum())

Missing values in features:
0

Missing values in target:
0

In [12]:
final_dataset = X_encoded.copy()

final_dataset["Revenue(INR)"] = y.values

output_path = "../../Dataset/processed/final_dataset.csv"

final_dataset.to_csv(output_path, index=False)

print("Final dataset saved successfully")
print(output_path)

Final dataset saved successfully
../../Dataset/processed/final_dataset.csv

In [13]:
final_dataset.head()

,Number_of_Screens,Budget(INR),Release_Period_Normal,Whether_Remake_Yes,Whether_Franchise_Yes,Genre_adult,Genre_animation,Genre_comedy,Genre_documentary,Genre_drama,...,Music_Director_Vivek Prakash,Music_Director_Vivek Priyadarshan,Music_Director_Wayne Sharpe,Music_Director_Yasin Darbar,Music_Director_Yuvan Shankar Raja,Music_Director_Zakir Hussain,Music_Director_Zubeen Garg,Music_Director_Zubin Balaporia,Music_Director_Zubunnisa Bangash,Revenue(INR)
0,5,85000,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,5000000.0
1,75,825000,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,15000000.0
2,525,56700000,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,75000000.0
3,800,4500000,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,210000000.0
4,1,1075000,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1000000.0

In [14]:
print("Final dataset shape:", final_dataset.shape)
print("Number of input features:", X_encoded.shape[1])
print("Target:", "Revenue(INR)")

Final dataset shape: (1696, 2461)
Number of input features: 2460
Target: Revenue(INR)